CREATE TABLE contacts(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    type VARCHAR(20) NOT NULL,
    label VARCHAR(100) NOT NULL,
    author_id BIGINT NOT NULL,
    CONSTRAINT fk_contacts_author FOREIGN KEY (author_id) REFERENCES authors(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;